package com.tweetapp.lambda.dto;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "TWEETS_TABLE_NAME")
public class TweetsDto {
	private static final String TWEETS_TABLE_NAME = System.getenv("TWEETS_TABLE");
	@DynamoDBAttribute
	private String tweet;
	@DynamoDBAttribute
	private String userTweetId;

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String tweetId;
	@DynamoDBAttribute
	private Long like;
	@DynamoDBAttribute
	private List<Reply> reply;
	@DynamoDBAttribute
	private String dateOfPost;
	@DynamoDBAttribute
	private String timeOfPost;

}
